### ISSUE TITLE
Plugin version 0.9.8.9 is not compatible with WordPress 4.6

### ISSUE THREAD

**Issue by suresh17061988** [craftsmancoding/custom-content-type-manager#41]
I upgraded my WordPress from 4.2 to 4.6 and this plugin stopped working , Plugin's custom field and custom content type is showing blank page inside the admin. Could you suggest what we should do to solve this issue ??

**Comment by jpSimkins** [comment]
It works fine for me on 4.6

**Comment by suresh17061988** [comment]
Good to know, It worked for me once deleted cache...
Thanks
